// Generated by scripts/gen-properties.mjs from the Glasser OpenAPI document. Do not edit.
import type { INodeProperties } from 'n8n-workflow';

/** Solution the node calls: POST /v1/solutions/gtm/<resource>. */
export const SOLUTION = 'gtm';

/** Per resource: the contract field the Operation dropdown maps to, and which string fields the API takes as arrays (the node splits commas). */
export const RESOURCE_META: Record<string, { operation: string; lists: string[] }> = {
	people_search: {
		operation: 'action',
		lists: ['job_titles', 'locations'],
	},
	company_intelligence: {
		operation: 'action',
		lists: [],
	},
	seo_research: {
		operation: 'action',
		lists: ['keywords'],
	},
	web_research: {
		operation: 'action',
		lists: [],
	},
	social_research: {
		operation: 'mode',
		lists: [],
	},
	market_data: {
		operation: 'action',
		lists: [],
	},
};

/** Parameters that only shape the form (which fields to show) and are never sent to the API. */
export const NODE_ONLY: ReadonlySet<string> = new Set(['lookupBy', 'searchBy']);

export const properties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Company',
				value: 'company_intelligence',
			},
			{
				name: 'Market Data',
				value: 'market_data',
			},
			{
				name: 'Person',
				value: 'people_search',
			},
			{
				name: 'SEO',
				value: 'seo_research',
			},
			{
				name: 'Social',
				value: 'social_research',
			},
			{
				name: 'Web Research',
				value: 'web_research',
			},
		],
		default: 'people_search',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			'Default search. search: people matching job_titles, seniorities, locations, company_domain or keywords (at least one); a filter is never silently dropped — under auto a Provider that cannot apply one of the given filters is skipped, a named Provider that cannot is refused with 400. enrich: one person from linkedin_url, email, or full_name plus company_domain. find_email: the work email of full_name at company_domain.',
		displayOptions: {
			show: {
				resource: ['people_search'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Enrich',
				value: 'enrich',
				action: 'Enrich a person',
			},
			{
				name: 'Find Work Email',
				value: 'find_email',
				action: 'Find a work email',
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search people',
			},
		],
		default: 'search',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['search'],
			},
		},
		options: [
			{
				displayName: 'Company Domain',
				name: 'company_domain',
				description:
					'A website domain such as stripe.com. A full URL is accepted and reduced to its host.',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Job Titles',
				name: 'job_titles',
				description: "Job titles, e.g. 'CTO, VP Engineering'.. Comma-separated, up to 20.",
				type: 'string',
				default: '',
			},
			{
				displayName: 'Locations',
				name: 'locations',
				description: 'Cities, states or countries.. Comma-separated, up to 20.',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Seniorities',
				name: 'seniorities',
				description: 'Seniority levels',
				type: 'multiOptions',
				options: [
					{
						name: 'C-Suite',
						value: 'c_suite',
					},
					{
						name: 'Director',
						value: 'director',
					},
					{
						name: 'Entry',
						value: 'entry',
					},
					{
						name: 'Founder',
						value: 'founder',
					},
					{
						name: 'Head',
						value: 'head',
					},
					{
						name: 'Intern',
						value: 'intern',
					},
					{
						name: 'Manager',
						value: 'manager',
					},
					{
						name: 'Owner',
						value: 'owner',
					},
					{
						name: 'Partner',
						value: 'partner',
					},
					{
						name: 'Senior',
						value: 'senior',
					},
					{
						name: 'VP',
						value: 'vp',
					},
				],
				default: [],
			},
		],
	},
	{
		displayName: 'Lookup By',
		name: 'lookupBy',
		type: 'options',
		required: true,
		noDataExpression: true,
		description: 'Which identifier the person is looked up by',
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['enrich'],
			},
		},
		options: [
			{
				name: 'Email',
				value: 'email',
			},
			{
				name: 'LinkedIn URL',
				value: 'linkedin_url',
			},
			{
				name: 'Name and Company',
				value: 'name_company',
			},
		],
		default: 'linkedin_url',
	},
	{
		displayName: 'LinkedIn URL',
		name: 'linkedin_url',
		description:
			"The person's LinkedIn profile URL, linkedin.com/in/&lt;slug&gt;. Not a company page.",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['enrich'],
				lookupBy: ['linkedin_url'],
			},
		},
	},
	{
		displayName: 'Email',
		name: 'email',
		description: 'An email address',
		type: 'string',
		default: '',
		placeholder: 'name@email.com',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['enrich'],
				lookupBy: ['email'],
			},
		},
	},
	{
		displayName: 'Full Name',
		name: 'full_name',
		description: "The person's full name, e.g. 'Patrick Collison'",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['enrich'],
				lookupBy: ['name_company'],
			},
		},
	},
	{
		displayName: 'Company Domain',
		name: 'company_domain',
		description:
			'A website domain such as stripe.com. A full URL is accepted and reduced to its host.',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['enrich'],
				lookupBy: ['name_company'],
			},
		},
	},
	{
		displayName: 'Full Name',
		name: 'full_name',
		description: "The person's full name, e.g. 'Patrick Collison'",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['find_email'],
			},
		},
	},
	{
		displayName: 'Company Domain',
		name: 'company_domain',
		description:
			'A website domain such as stripe.com. A full URL is accepted and reduced to its host.',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['people_search'],
				operation: ['find_email'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['people_search'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of apollo, pdl, leadmagic, zoominfo, hunter, prospeo. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Apollo',
						value: 'apollo',
					},
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'Hunter',
						value: 'hunter',
					},
					{
						name: 'LeadMagic',
						value: 'leadmagic',
					},
					{
						name: 'People Data Labs',
						value: 'pdl',
					},
					{
						name: 'Prospeo',
						value: 'prospeo',
					},
					{
						name: 'ZoomInfo',
						value: 'zoominfo',
					},
				],
				default: 'auto',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			'Default enrich. enrich: profile and firmographics; tech_stack; traffic; competitors: businesses similar to the company (for the domains it competes with in Google results use seo_research organic_competitors); funding; news. All take domain.',
		displayOptions: {
			show: {
				resource: ['company_intelligence'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Competitors',
				value: 'competitors',
				action: 'Get competitors',
			},
			{
				name: 'Enrich',
				value: 'enrich',
				action: 'Enrich a company',
			},
			{
				name: 'Funding Rounds',
				value: 'funding',
				action: 'Get funding rounds',
			},
			{
				name: 'News',
				value: 'news',
				action: 'Get company news',
			},
			{
				name: 'Technology Stack',
				value: 'tech_stack',
				action: 'Get the technology stack',
			},
			{
				name: 'Website Traffic',
				value: 'traffic',
				action: 'Get website traffic',
			},
		],
		default: 'enrich',
	},
	{
		displayName: 'Domain',
		name: 'domain',
		description:
			'A website domain such as stripe.com. A full URL is accepted and reduced to its host.',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['company_intelligence'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['company_intelligence'],
			},
		},
		options: [
			{
				displayName: 'Country',
				name: 'country',
				description:
					'Country as a two-letter ISO code or a country name, e.g. us, gb, de, Germany. Default us. An unsupported country is refused with the supported list.',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['company_intelligence'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of apollo, pdl, hunter, prospeo, predictleads, leadmagic, builtwith, dataforseo, ahrefs, apify, exa, serper. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Ahrefs',
						value: 'ahrefs',
					},
					{
						name: 'Apify',
						value: 'apify',
					},
					{
						name: 'Apollo',
						value: 'apollo',
					},
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'BuiltWith',
						value: 'builtwith',
					},
					{
						name: 'DataForSEO',
						value: 'dataforseo',
					},
					{
						name: 'Exa',
						value: 'exa',
					},
					{
						name: 'Hunter',
						value: 'hunter',
					},
					{
						name: 'LeadMagic',
						value: 'leadmagic',
					},
					{
						name: 'People Data Labs',
						value: 'pdl',
					},
					{
						name: 'PredictLeads',
						value: 'predictleads',
					},
					{
						name: 'Prospeo',
						value: 'prospeo',
					},
					{
						name: 'Serper',
						value: 'serper',
					},
				],
				default: 'auto',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			'Default keyword_overview. keyword_overview takes keywords (several at once); keyword_ideas and serp take exactly one keyword in keywords; domain_overview, ranked_keywords, organic_competitors (domains ranking for the same keywords), backlinks_overview, backlinks, referring_domains and domain_rating take domain.',
		displayOptions: {
			show: {
				resource: ['seo_research'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Backlink Totals',
				value: 'backlinks_overview',
				action: 'Get backlink totals',
			},
			{
				name: 'Backlinks List',
				value: 'backlinks',
				action: 'List backlinks',
			},
			{
				name: 'Domain Organic Overview',
				value: 'domain_overview',
				action: 'Get a domain organic overview',
			},
			{
				name: 'Domain Rating',
				value: 'domain_rating',
				action: 'Get domain rating',
			},
			{
				name: 'Google Results for a Keyword',
				value: 'serp',
				action: 'Get search results for a keyword',
			},
			{
				name: 'Keyword Ideas',
				value: 'keyword_ideas',
				action: 'Get keyword ideas',
			},
			{
				name: 'Keyword Metrics',
				value: 'keyword_overview',
				action: 'Get keyword metrics',
			},
			{
				name: 'Organic Search Competitors',
				value: 'organic_competitors',
				action: 'Get organic search competitors',
			},
			{
				name: 'Ranked Keywords',
				value: 'ranked_keywords',
				action: 'Get ranked keywords',
			},
			{
				name: 'Referring Domains',
				value: 'referring_domains',
				action: 'List referring domains',
			},
		],
		default: 'keyword_overview',
	},
	{
		displayName: 'Keywords',
		name: 'keywords',
		description: "Keywords to look up, e.g. 'espresso machine'.. Comma-separated, up to 20.",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['seo_research'],
				operation: ['keyword_overview', 'keyword_ideas', 'serp'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['seo_research'],
				operation: ['keyword_overview', 'keyword_ideas', 'serp'],
			},
		},
		options: [
			{
				displayName: 'Country',
				name: 'country',
				description:
					'Country as a two-letter ISO code or a country name, e.g. us, gb, de, Germany. Default us. An unsupported country is refused with the supported list.',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		description:
			'A website domain such as stripe.com. A full URL is accepted and reduced to its host.',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['seo_research'],
				operation: [
					'domain_overview',
					'ranked_keywords',
					'organic_competitors',
					'backlinks_overview',
					'backlinks',
					'referring_domains',
					'domain_rating',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['seo_research'],
				operation: [
					'domain_overview',
					'ranked_keywords',
					'organic_competitors',
					'backlinks_overview',
					'backlinks',
					'referring_domains',
					'domain_rating',
				],
			},
		},
		options: [
			{
				displayName: 'Country',
				name: 'country',
				description:
					'Country as a two-letter ISO code or a country name, e.g. us, gb, de, Germany. Default us. An unsupported country is refused with the supported list.',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['seo_research'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of semrush, serpstat, dataforseo, ahrefs, serper. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Ahrefs',
						value: 'ahrefs',
					},
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'DataForSEO',
						value: 'dataforseo',
					},
					{
						name: 'Semrush',
						value: 'semrush',
					},
					{
						name: 'Serper',
						value: 'serper',
					},
					{
						name: 'Serpstat',
						value: 'serpstat',
					},
				],
				default: 'auto',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			'Default search. search, news, places, scholar, shopping, images, videos and answer take query; scrape and similar take URL.',
		displayOptions: {
			show: {
				resource: ['web_research'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Academic Papers',
				value: 'scholar',
				action: 'Search academic papers',
			},
			{
				name: 'Answer From the Web',
				value: 'answer',
				action: 'Answer a question from the web',
			},
			{
				name: 'Images',
				value: 'images',
				action: 'Search images',
			},
			{
				name: 'News',
				value: 'news',
				action: 'Search news',
			},
			{
				name: 'Places',
				value: 'places',
				action: 'Search places',
			},
			{
				name: 'Read a Web Page',
				value: 'scrape',
				action: 'Read a web page',
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search the web',
			},
			{
				name: 'Shopping',
				value: 'shopping',
				action: 'Search shopping',
			},
			{
				name: 'Similar Pages',
				value: 'similar',
				action: 'Find similar pages',
			},
			{
				name: 'Videos',
				value: 'videos',
				action: 'Search videos',
			},
		],
		default: 'search',
	},
	{
		displayName: 'Query',
		name: 'query',
		description: 'Search phrase or question',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['web_research'],
				operation: [
					'search',
					'news',
					'places',
					'scholar',
					'shopping',
					'images',
					'videos',
					'answer',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['web_research'],
				operation: [
					'search',
					'news',
					'places',
					'scholar',
					'shopping',
					'images',
					'videos',
					'answer',
				],
			},
		},
		options: [
			{
				displayName: 'Country',
				name: 'country',
				description:
					'Country for search-type actions, as a two-letter ISO code or a country name. Default us. Not for scrape or similar. Refused with 400 when the named provider cannot apply it.',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		description: 'A full http(s) URL',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['web_research'],
				operation: ['scrape', 'similar'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['web_research'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of serper, serpapi, exa, dataforseo. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'DataForSEO',
						value: 'dataforseo',
					},
					{
						name: 'Exa',
						value: 'exa',
					},
					{
						name: 'SerpApi',
						value: 'serpapi',
					},
					{
						name: 'Serper',
						value: 'serper',
					},
				],
				default: 'auto',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			"Default search. search: posts matching query. profile: the account itself — bio, follower counts, links — from handle (reddit: the subreddit; linkedin: URL of a person's profile or a company page). feed: the account's recent posts or videos, from handle (linkedin: URL of a company page). post: one post or video from URL. find: an account's other social profiles, from handle (linkedin: URL of a person's profile; reddit: subreddits matching query). Every platform supports every mode.",
		displayOptions: {
			show: {
				resource: ['social_research'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'Find Social Profiles',
				value: 'find',
				action: 'Find social profiles',
			},
			{
				name: 'One Post',
				value: 'post',
				action: 'Get one post',
			},
			{
				name: 'Profile',
				value: 'profile',
				action: 'Get a social profile',
			},
			{
				name: 'Recent Posts',
				value: 'feed',
				action: 'Get recent posts',
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search social posts',
			},
		],
		default: 'search',
	},
	{
		displayName: 'Platform',
		name: 'platform',
		type: 'options',
		options: [
			{
				name: 'Instagram',
				value: 'instagram',
			},
			{
				name: 'LinkedIn',
				value: 'linkedin',
			},
			{
				name: 'Reddit',
				value: 'reddit',
			},
			{
				name: 'TikTok',
				value: 'tiktok',
			},
			{
				name: 'X',
				value: 'x',
			},
			{
				name: 'YouTube',
				value: 'youtube',
			},
		],
		default: 'reddit',
		required: true,
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
			},
		},
	},
	{
		displayName: 'Query',
		name: 'query',
		description: 'Search phrase or question',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
				operation: ['search'],
			},
		},
	},
	{
		displayName: 'Handle',
		name: 'handle',
		description: 'A username without @, or a subreddit name without r/',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
				operation: ['profile', 'feed'],
			},
		},
	},
	{
		displayName: 'URL',
		name: 'url',
		description: 'A full http(s) URL',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
				operation: ['post'],
			},
		},
	},
	{
		displayName: 'Handle',
		name: 'handle',
		description: 'A username without @, or a subreddit name without r/',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
				operation: ['find'],
			},
			hide: {
				platform: ['reddit'],
			},
		},
	},
	{
		displayName: 'Query',
		name: 'query',
		description: 'Search phrase or question',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['social_research'],
				operation: ['find'],
				platform: ['reddit'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['social_research'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of scrapecreators, apify, tikhub, pdl. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Apify',
						value: 'apify',
					},
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'People Data Labs',
						value: 'pdl',
					},
					{
						name: 'ScrapeCreators',
						value: 'scrapecreators',
					},
					{
						name: 'TikHub',
						value: 'tikhub',
					},
				],
				default: 'auto',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		description:
			'Property_value and property_rent take address. property_search, listings_sale and listings_rental take address, or city plus state, or zip. market_stats takes zip. stock_quote takes symbol.',
		displayOptions: {
			show: {
				resource: ['market_data'],
			},
		},
		type: 'options',
		noDataExpression: true,
		options: [
			{
				name: 'For-Sale Listings',
				value: 'listings_sale',
				action: 'List listings for sale',
			},
			{
				name: 'Property Records',
				value: 'property_search',
				action: 'Search property records',
			},
			{
				name: 'Property Value Estimate',
				value: 'property_value',
				action: 'Estimate a property value',
			},
			{
				name: 'Rent Estimate',
				value: 'property_rent',
				action: 'Estimate rent',
			},
			{
				name: 'Rental Listings',
				value: 'listings_rental',
				action: 'List rental listings',
			},
			{
				name: 'Stock Quote',
				value: 'stock_quote',
				action: 'Get a stock quote',
			},
			{
				name: 'ZIP Market Statistics',
				value: 'market_stats',
				action: 'Get ZIP market statistics',
			},
		],
		default: 'property_value',
	},
	{
		displayName: 'Address',
		name: 'address',
		description: "US street address, e.g. '5500 Grand Lake Dr, San Antonio, TX 78244'",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_value', 'property_rent'],
			},
		},
	},
	{
		displayName: 'Search By',
		name: 'searchBy',
		type: 'options',
		required: true,
		noDataExpression: true,
		description: 'How the area or property is identified',
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_search', 'listings_sale', 'listings_rental'],
			},
		},
		options: [
			{
				name: 'Address',
				value: 'address',
			},
			{
				name: 'City and State',
				value: 'city_state',
			},
			{
				name: 'ZIP Code',
				value: 'zip',
			},
		],
		default: 'address',
	},
	{
		displayName: 'Address',
		name: 'address',
		description: "US street address, e.g. '5500 Grand Lake Dr, San Antonio, TX 78244'",
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_search', 'listings_sale', 'listings_rental'],
				searchBy: ['address'],
			},
		},
	},
	{
		displayName: 'City',
		name: 'city',
		description: 'US city name; use with state',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_search', 'listings_sale', 'listings_rental'],
				searchBy: ['city_state'],
			},
		},
	},
	{
		displayName: 'State',
		name: 'state',
		description: 'Two-letter US state code, e.g. TX',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_search', 'listings_sale', 'listings_rental'],
				searchBy: ['city_state'],
			},
		},
	},
	{
		displayName: 'ZIP Code',
		name: 'zip',
		description: 'Five-digit US ZIP code',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['property_search', 'listings_sale', 'listings_rental'],
				searchBy: ['zip'],
			},
		},
	},
	{
		displayName: 'ZIP Code',
		name: 'zip',
		description: 'Five-digit US ZIP code',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['market_stats'],
			},
		},
	},
	{
		displayName: 'Symbol',
		name: 'symbol',
		description: 'Ticker with exchange, e.g. AAPL:NASDAQ',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['market_data'],
				operation: ['stock_quote'],
			},
		},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['market_data'],
			},
		},
		options: [
			{
				displayName: 'Provider',
				name: 'provider',
				description:
					'Data provider: auto (default) or one of rentcast, serpapi. Name one only when the caller asks for that vendor.',
				type: 'options',
				options: [
					{
						name: 'Auto (Glasser Picks)',
						value: 'auto',
					},
					{
						name: 'RentCast',
						value: 'rentcast',
					},
					{
						name: 'SerpApi',
						value: 'serpapi',
					},
				],
				default: 'auto',
			},
		],
	},
];
